### ISSUE TITLE
Doesn't load module in install globally

### ISSUE THREAD

**Issue by laiso** [aseemk/requireDir#10]
> $ node -v
> v0.10.35 # under nvm

```
$ npm install --global require-dir
$ node -e "var dir=require('require-dir')('.'); console.log(dir)"

module.js:340
    throw err;
          ^
Error: Cannot find module 'require-dir'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:9
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:559:25)
    at startup (node.js:80:7)
    at node.js:929:3
```

```
$ npm install require-dir
$ node -e "var dir=require('require-dir')('.'); console.log(dir)"
{} 
```

**Comment by laiso** [comment]
Oops, this is nvm problem.
sorry :disappointed: 

```
$ /usr/local/bin/npm install --global require-dir
require-dir@0.1.0 /usr/local/lib/node_modules/require-dir
$ /usr/local/bin/node -e "var dir=require('require-dir')('.'); console.log(dir)"
{}
```

**Comment by aseemk** [comment]
No problem, thanks for closing. =)
