### ISSUE TITLE
broken after update to node.js 4.0

### ISSUE THREAD

**Issue by sosnovskyas** [aseemk/requireDir#20]
after update to node.js 4.0 all my projects who have requireDir was broken. 
my gulp config

```
'use strict';
var requireDir = require('require-dir');
requireDir('./gulp/tasks', {recurse: true});
```

if 

```
var gulp = require('gulp');
gulp.task('default', function() {
});
```

all fine

but if my config, then 

```
Failed to list gulp tasks in fitness/gulpfile.js: process finished with exit code 1 (a non-zero exit code means an error)
 * Edit settings

$ /usr/local/bin/node /usr/local/lib/node_modules/gulp/bin/gulp.js --no-color --gulpfile /Users/ass/projects/fitness/gulpfile.js --tasks
module.js:338
    throw err;
    ^

Error: Cannot find module 'gulp-util'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/ass/projects/fitness/gulpfile.js:2:13)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

Process finished with exit code 1
```

in WebStorm

and

```
$ gulp
Segmentation fault: 11
```

in pure console

**Comment by sosnovskyas** [comment]
I that could help this situation must was delete all node_modules (rm -rf) and clear cache (npm cache clean) and reinstall packages (npm i). after this all was right.

**Comment by GerHobbelt** [comment]
This problem was not reproducible on node v4.1.2 (Windows); sounds more like some of those installed packages had to be reinstalled after the node4 update anyway.

**Comment by contra** [comment]
shouldn't be an issue anymore, let me know if it is and i can reopen
